version: '3.8'

services:
  #imagen para base de datos(mariadb)
  db:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: caballo_homosexual_de_las_montañas
      MARIADB_DATABASE: lockey
    volumes:
      - mariadb_data:/var/lib/mysql
  #imagen para el frontend
  frontend:
    build: web_server/.
    volumes:
    - type: bind
      source: ./frontend
      target: /var/marlin/html
      read_only: true
  #   depends_on:
  #     - auth
  #     - crud
  # #imagen para el microservicio de autenticación
  # auth:
  #   build: auth/.
  #   depends_on:
  #     - mahi
  # #imagen para el microservicio de CRUD
  # crud:
  #   build: crud/.
  #   depends_on:
  #     - mahi
  #imagen para el microservicio de Marcelo
  mahi:
    build: mahi/.
    depends_on:
      - db
volumes:
  mariadb_data: