# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/contrasenas.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'protos/contrasenas.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18protos/contrasenas.proto\x12\x08usuarios\"\\\n\rCreateRequest\x12\x12\n\nplataforma\x18\x01 \x01(\t\x12\x16\n\x0enombre_usuario\x18\x02 \x01(\t\x12\x0c\n\x04pass\x18\x03 \x01(\t\x12\x11\n\thash_user\x18\x04 \x01(\t\"6\n\x0e\x43reateResponse\x12\x0f\n\x07mensaje\x18\x01 \x01(\t\x12\x13\n\x0bstatus_code\x18\x02 \x01(\x05\" \n\x0bReadRequest\x12\x11\n\thash_user\x18\x01 \x01(\t\"\x88\x01\n\x0cReadResponse\x12&\n\nlista_pass\x18\x01 \x03(\x0b\x32\x12.usuarios.ItemPass\x12\x15\n\x08\x65rr_code\x18\x02 \x01(\x05H\x00\x88\x01\x01\x12\x1a\n\rmensaje_error\x18\x03 \x01(\tH\x01\x88\x01\x01\x42\x0b\n\t_err_codeB\x10\n\x0e_mensaje_error\"T\n\x08ItemPass\x12\x12\n\nplataforma\x18\x01 \x01(\t\x12\x11\n\tuser_name\x18\x02 \x01(\t\x12\x0e\n\x06passwd\x18\x03 \x01(\t\x12\x11\n\thash_user\x18\x04 \x01(\t\"6\n\nDelRequest\x12\x12\n\nplataforma\x18\x01 \x01(\t\x12\x14\n\x0chash_usuario\x18\x02 \x01(\t\"\x1e\n\x0b\x44\x65lResponse\x12\x0f\n\x07mensaje\x18\x01 \x01(\t\"Y\n\rUpdateRequest\x12\x11\n\thash_user\x18\x01 \x01(\t\x12\x12\n\nplataforma\x18\x02 \x01(\t\x12\x11\n\tuser_name\x18\x03 \x01(\t\x12\x0e\n\x06passwd\x18\x04 \x01(\t\"6\n\x0eUpdateResponse\x12\x13\n\x0bstatus_code\x18\x01 \x01(\x05\x12\x0f\n\x07mensaje\x18\x02 \x01(\t2\x82\x02\n\x0bPassService\x12\x39\n\x08ReadPass\x12\x15.usuarios.ReadRequest\x1a\x16.usuarios.ReadResponse\x12?\n\nCreatePass\x12\x17.usuarios.CreateRequest\x1a\x18.usuarios.CreateResponse\x12\x36\n\x07\x44\x65lPass\x12\x14.usuarios.DelRequest\x1a\x15.usuarios.DelResponse\x12?\n\nUpdatePass\x12\x17.usuarios.UpdateRequest\x1a\x18.usuarios.UpdateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.contrasenas_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEREQUEST']._serialized_start=38
  _globals['_CREATEREQUEST']._serialized_end=130
  _globals['_CREATERESPONSE']._serialized_start=132
  _globals['_CREATERESPONSE']._serialized_end=186
  _globals['_READREQUEST']._serialized_start=188
  _globals['_READREQUEST']._serialized_end=220
  _globals['_READRESPONSE']._serialized_start=223
  _globals['_READRESPONSE']._serialized_end=359
  _globals['_ITEMPASS']._serialized_start=361
  _globals['_ITEMPASS']._serialized_end=445
  _globals['_DELREQUEST']._serialized_start=447
  _globals['_DELREQUEST']._serialized_end=501
  _globals['_DELRESPONSE']._serialized_start=503
  _globals['_DELRESPONSE']._serialized_end=533
  _globals['_UPDATEREQUEST']._serialized_start=535
  _globals['_UPDATEREQUEST']._serialized_end=624
  _globals['_UPDATERESPONSE']._serialized_start=626
  _globals['_UPDATERESPONSE']._serialized_end=680
  _globals['_PASSSERVICE']._serialized_start=683
  _globals['_PASSSERVICE']._serialized_end=941
# @@protoc_insertion_point(module_scope)
