syntax = "proto3";
package usuarios;

// Definición del servicio
service PassService {
  rpc ReadPass (ReadRequest) returns (ReadResponse);
  rpc CreatePass (CreateRequest) returns (CreateResponse);
  rpc DelPass (DelRequest) returns (DelResponse);
  rpc UpdatePass (UpdateRequest) returns (UpdateResponse);
}

// Mensajes de solicitud y respuesta
message CreateRequest {
  string plataforma=1;
  String nombre_usuario=2;
  string pass=3;
  string hash_user=4;
}

message CreateResponse {
    string mensaje=1;
    int32 status_code=2;
}
message ReadRequest{
    string hash_user=1;
}
message ReadResponse{
    repeated ItemPass lista_pass=1;
    optional int32 err_code=2;
    optional string mensaje_error=3;
}
message ItemPass{
    string plataforma=1;
    string user_name=2;
    string passwd=3;
    string hash_user=4;
}
message DelRequest{
    string plataforma=1;
    string hash_usuario=2;
}
message DelResponse{
    string mensaje=1;
    
}
message UpdateRequest{
    string hash_user=1;
    string plataforma=2;
    string user_name=3;
    string passwd=4;
}
message UpdateResponse{
    int32 status_code=1;
    string mensaje=2;
}