FROM rust:1.98 as builder
WORKDIR /usr/src/mahi
COPY mahi/ .
RUN cargo install --path .

FROM debian:latest
RUN apt-get update && apt-get install -y extra-runtime-dependencies && rm -rf /var/lib/apt/lists/*
COPY --from=builder /usr/local/cargo/bin/mahi /usr/local/bin/mahi
CMD ["mahi"]
