FROM rust:1.98 as builder
WORKDIR /usr/src/marcelo
COPY marcelo/ .
RUN cargo install --path .

FROM debian:latests
RUN apt-get update && apt-get install -y extra-runtime-dependencies && rm -rf /var/lib/apt/lists/*
COPY --from=builder /usr/local/cargo/bin/marcelo /usr/local/bin/marcelo
CMD ["marcelos"]
